apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  labels:
    app: webserver-apache
spec:
  selector:
    matchLabels:
      app: webserver-apache
  replicas: 2
  template:
    metadata:
      labels:
        app: webserver-apache
    spec:
      containers:
      - name: apache
        image: bitnami/apache:latest
        ports:
        - containerPort: 80
