apiVersion: v1
kind: Pod
metadata:
  name: webserver
  labels:
    env: production
    owner: hamza
    webserver: nginx
    name: mon-nginx
    contry: FRANCE
spec:
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
