apiVersion: v1
kind: Pod
metadata:
  name: "two-container-pod"
  namespace: default
  labels:
    app: "two-container-pod"
spec:
  restartPolicy: Never
  volumes:
    - name: shared-area
      emptyDir: {}
  containers:
    - name: nginx-container
      image: nginx
      volumeMounts:
      - name: shared-area
        mountPath: /usr/share/nginx/html
    - name: ubuntu-container
      image: ubuntu
      volumeMounts:
        - name: shared-area
          mountPath: "/pod-area"
    # - command: ["/bash"]
    #   args: ["-c", "echo Hello > /pod-area/index.html"]


